pipeline {
    agent any
    stages {
        stage('Build') {
            steps{
                sh 'mvn -f mi-proyecto/pom.xml -B -Dstyle.color=never clean install'
            }
        }
        stage('Test') {
            steps{
                sh 'mvn -f mi-proyecto/pom.xml -B -Dstyle.color=never test'
            }
        }
        stage('Deploy') {
            steps{
                echo "Simulando un despliegue a servidor de aplicaciones"
            }
        }
    }
    post {
        always {
            echo "Siempre se ejecutara esta seccion"
        }
        success {
            echo "Exito: aca se ejecuta si todo el pipeline fue exitoso"
        }
        failure {
            echo "Fallo: aca se ejecuta si el pipeline falla"
        }
    }
}